config/routes.rb
Rails.application.routes.draw do

  root 'sessions#welcome'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'




  delete '/logout', to: "sessions#destroy" 




  get '/auth/:provider/callback' => 'sessions#omniauth'



  resources :users
  resources :brands do 
    resources :laptops
  end 
  resources :reviews


  get '/laptops/most_expensive', to: 'laptops#expensive', as: 'expensive'

  resources :laptops do 
    resources :reviews
  end 

  




end 

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :laptops
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_brand, only: [:show, :destroy, :edit, :update]
    
    def index 
        @brands = Brand.all
    end 

    def show 
     
    end 

    def destroy 
        @brand.destroy 
        redirect_to brands_path
    end 

    def edit 
      
    end 

    def update  
        @brand.update(params.require(:brand).permit(:name))
        redirect_to  brand_path(@brand)
    end 


    private 

    def set_brand
        @brand = Brand.find_by(params[:id])
    end 
 
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/edit.html.erb
<h1>Edit for <%= @brand.name %> </h1>

<%= form_for (@brand) do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.submit %>
<%end%>

app/views/brands/index.html.erb
<h1>All brands </h1><br><br>

<% @brands.each do |brand| %>
  <h3><p><%= link_to brand.name, brand_laptops_path(brand) %></p><h3><br
    <%end%>

app/views/brands/show.html.erb
<h2> Brand: <%= @brand.name %> </h2><br>
 <%= link_to( "Edit" , edit_brand_path ) %> -  <%= link_to( "Delete" , brand_path(@brand), method: 'delete') %>