config/routes.rb
Rails.application.routes.draw do

  root 'sessions#welcome'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'




  delete '/logout', to: "sessions#destroy" 




  get '/auth/:provider/callback' => 'sessions#omniauth'



  resources :users
  resources :brands do 
    resources :laptops
  end 
  resources :reviews


  get '/laptops/most_expensive', to: 'laptops#expensive', as: 'expensive'

  resources :laptops do 
    resources :reviews
  end 

  




end 

app/models/laptop.rb
class Laptop < ApplicationRecord
    belongs_to :brand 
    belongs_to :user 

    has_many :reviews
    has_many :users, through: :reviews


    validates :brand, :color, :condition, :price , presence: true 
    validates :price, numericality: { only_integer: true, greater_than: 0}
    validates :color, uniqueness: {scope: :brand, message: "has already been used with that brand"}
    validate :color_check
    
    
    scope :order_by_ratings, -> {joins(:reviews).group(:id).order('avg(stars) desc')}
    scope :order_by_prices, -> {order(:price)}
    scope :new_laptops, -> {where('condition = ?', 'new')}
    scope :most_expensive, -> {where(price: Laptop.maximum('price')).last}
    
  
    
    def brand_attributes=(attributes)
        if !attributes[:name].blank?
            self.brand = Brand.find_or_create_by(attributes)
        end 
    end 

    def color_check 
        if color.split(" ").count > 3 
            errors.add(:color, "must be 1 or 2 words")
        end 
    end 

  
    def color_and_brand 
        "#{color} - #{brand.try(:name)}"
    end 

    def brand_name 
        brand.try(:name)
    end 

    def self.search(search)
        if search 
            brand = Brand.find_by(name: search)
            if brand
                self.where(brand_id: brand)
            else 
                all
            end 
        else 
           all
        end 
    end 


  



    
  

end 

app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_laptop, only: [:edit, :update, :show, :destroy]


    def index   
        if @brand = Brand.find_by_id(params[:brand_id])
           @laptops = @brand.laptops
        else 
           @laptops = Laptop.order_by_prices.search(params[:search])
        end 
    end 
    


    def show 
     
    end 



    def new 
        @laptop = Laptop.new 
        @laptop.build_brand
    end 


    def create
        @laptop = Laptop.new(laptop_params)
        @laptop.user_id = session[:user_id]

        if @laptop.save
            redirect_to laptop_path(@laptop)
        else 
            render :new 
        end 
    end 



    def edit 
    
    end 


    def update 
        @laptop.update(laptop_params)
        redirect_to laptop_path(@laptop)
    end 


    def destroy 
        @laptop.destroy
        redirect_to laptops_path
    end 
    



   
    def expensive 
        @laptop = Laptop.most_expensive
    end 


  

    private 

    def laptop_params
        params.require(:laptop).permit(:color, :condition, :price, :brand_id, :search, brand_attributes: [:name])
    end 

    def set_laptop
        @laptop = Laptop.find_by_id(params[:id])
    end 
end

app/helpers/laptops_helper.rb
module LaptopsHelper

    def display_header_brand(brand)
        if @brand 
            content_tag(:h1, "#{@brand.name}") 
        else 
            content_tag(:h1, "All the Laptops") 
        end
    end 

    
end 

app/views/laptops/_form.html.erb
<%= form_for(@laptop) do |f|%>


  <%= f.label :color %>
  <%= f.text_field :color %>
  <br><br>

  <%= f.label :condition %>
  <%= f.text_field :condition %>
  <br><br>

  <%= f.label :price %>
  <%= f.number_field :price %>
  <br><br>


  <h4> Select an exist Brand: </h4>
  <div>
    <%= f.collection_select :brand_id , Brand.all, :id, :name, include_blank: 'Select One' %>
  </div>

  <h4> Or create a new Brand: </h4>
  <div>
    <%= f.fields_for :brand do |b| %>
    <%= b.label :name %>
    <%= b.text_field :name %>
    <%end%>
  </div>

  <br><br>
  <%= f.submit  %>
  <br>
  <%end%>

app/views/laptops/edit.html.erb
<h1>Edit the laptop </h1>
<%= render partial: 'layouts/errors', locals: {object: @laptop} %>
<%= render 'form' %>

app/views/laptops/expensive.html.erb
<h1> <%= @laptop.color_and_brand %> </h1>

<p>Condition: <%= @laptop.condition %></p>
<p>Price: $<%= @laptop.price%></p>

app/views/laptops/index.html.erb
<%= display_header_brand(@brand)%>

<h4> Search by Brand: </h4>
<%= form_tag(laptops_path, method: :get) do %>
    <%= text_field_tag(:search, params[:search]) %>
    <%= submit_tag ("Search") %>
<%end%>
<br><br>

<div>
<% @laptops.each do |laptop| %>

   Brand: <%= link_to laptop.brand.name, brand_path(laptop) %> - Price: <%= laptop.price %> - <%= link_to( "More details", laptop_path(laptop)) %><br>
              <p><%= link_to "Write a review", new_laptop_review_path(laptop) %></p>
              <p><% laptop.reviews.each do |laptop_review| %></p>
              <p> <%=laptop_review.stars%> stars</p><br>
              <%end%>
    <%end%>
</div>

app/views/laptops/new.html.erb
<h1> Create A new laptop </h1>
<%= render partial: 'layouts/errors', locals: {object: @laptop} %>
<%= render 'form' %>

app/views/laptops/show.html.erb
           <h2><%= @laptop.brand_name %></h2>
           <ul>
<p> Condition: <%= @laptop.condition %></p>
<p> Color: <%= @laptop.color %></p>
<p> Price: $<%= @laptop.price %></p>
           <%= link_to( "Delete" , laptop_path(@laptop), method: 'delete') %> |
           <%= link_to( "Edit" , edit_laptop_path ) %>
           </ul>