config/routes.rb
Rails.application.routes.draw do

  root 'sessions#welcome'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'




  delete '/logout', to: "sessions#destroy" 




  get '/auth/:provider/callback' => 'sessions#omniauth'



  resources :users
  resources :brands do 
    resources :laptops
  end 
  resources :reviews


  get '/laptops/most_expensive', to: 'laptops#expensive', as: 'expensive'

  resources :laptops do 
    resources :reviews
  end 

  




end 

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LaptopsSales</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
 <body>

 <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div>
    <ul class="nav navbar-nav">
    <li class="active"><a href='/'>Home</a></li>
    <% if logged_in? %>
  User: <%= current_user.username %>
  <li><%= link_to "Log Out", logout_path, method: :delete %></li>
  <li><%= link_to  "Add a Laptop", new_laptop_path %></li>
  <li><%= link_to "All Laptops", laptops_path %></li>
  <li> <%= link_to "Add a Review", new_review_path %></li>
  <li><%= link_to "All Reviews" , reviews_path %> </li>
  <li><%= link_to "All Brands", brands_path %></li>
  <li><%= link_to "Most expensive", expensive_path %></li>
  <%end%>
  </ul>
  </div>
  </div>
  </nav>
<body class="text-center" >
  <%= yield %>
  </body>

</body>
</html>